
services:
  backend:
    build: .
    container_name: cresfera_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:cresfera@db:5432/cresfera
    networks:
      - cresfera_network

  db:
    image: postgres:15
    container_name: cresfera_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cresfera
      POSTGRES_DB: cresfera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cresfera_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: cresfera_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cresfera.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - cresfera_network

volumes:
  postgres_data:

networks:
  cresfera_network:
